### ISSUE TITLE
The newer version of 1.4.1 doesn't working

### ISSUE THREAD

**Issue by ucok66** [Sibusten/derpibooru-downloader#21]
I don't know what went wrong, but I have to fall back to 1.4.1.
1.4.3:
![Capture](https://user-images.githubusercontent.com/46832396/56802370-0dce4000-684a-11e9-89a1-bc49779df295.PNG)
1.4.1:
![Capture1](https://user-images.githubusercontent.com/46832396/56802427-35250d00-684a-11e9-8916-7c9403d23f57.PNG)

also, I already check the SSL is working again but still https://github.com/Sibusten/derpibooru-downloader/issues/20#issuecomment-486125353

**Comment by Sibusten** [comment]
When you say the SSL is working again, do you mean that the problem is fixed for you too?

**Comment by ucok66** [comment]
around https://github.com/Sibusten/derpibooru-downloader/issues/20#issuecomment-486125353, but that didn't fix the version of 1.4.2 and above, only fixed this version

**Comment by Sibusten** [comment]
If you're running the command line version with a script, check to make sure the working directory is set to the directory where the program is

**Comment by ucok66** [comment]
thanks for the tip, but these things still exist.
```
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
```

**Comment by ucok66** [comment]
I have checked 49288003ff14abb926e628a1cc0798a4a9f1b2e3, that you changed the JSON configuration, but I still don't understand why this can cause `qt.network.ssl: QSslSocket :: connectToHostEncrypted: TLS initialization failed`

**Comment by Sibusten** [comment]
It could be an issue with the version of ssl in the build. I've added a version to the [1.4.3 release page](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.3) with updated ssl binaries. Try using that version and see if it fixes the problem.

**Comment by ucok66** [comment]
YES, it fixes the problem, finally, thanks. Also, I recommend you bring this fix to the upcoming release.

**Comment by Sibusten** [comment]
Good to hear. I've updated the 32 bit version as well and removed the old versions. I will use the new SSL binaries in future releases.
